name: restlib_core
description: A sample command-line application
dependencies:
  mime: any
  restlib_common:
    git: https://code.google.com/p/dart-restlib.common/
  restlib_parsing:
    git: https://code.google.com/p/dart-restlib.parsing/
dev_dependencies:
  restlib_testing:
    git: https://code.google.com/p/dart-restlib.testing/
  unittest: any
